#platform :ios, '5.1'
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.4'
pod 'SSKeychain', '~> 1.1.0'
pod 'MCSwipeTableViewCell', '~> 2.1.0'
# Sliding 2.0 requires 7.0
pod 'MMDrawerController', '~> 0.5.3'

# a submodule-less setup for development in both at the same time
pod 'PryvApiKit', :path => '../../sdk-objectivec-apple/PryvApiKit.podspec'

# after PryvApiKit would appear in Pods repository
pod 'PryvApiKit', :head

#pod 'PryvApiKit', :git => 'https://github.com/pryv/sdk-objectivec-apple.git', :commit => '9b065a16aaad41de8ee6c035cdf316bdde3c3292'
